package org.polaris2023.caft.quantum;

public enum QuantumUpgradeModule {
    COOLING_ACCELERATOR,
    JUMP_AMPLIFIER,
    STABILITY_CORE,
    ENERGY_EFFICIENCY_LOGIC_BOARD,
    INERTIA_RECTIFIER,
    COLLISION_PREDICTION_UNIT
}
