name: Build

on:
  push:

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Read mod version
        id: version
        shell: bash
        run: |
          mod_version="$(grep '^mod_version=' gradle.properties | cut -d'=' -f2- | tr -d '\r')"
          echo "mod_version=$mod_version" >> "$GITHUB_OUTPUT"

      - name: Setup JDK 21
        if: steps.version.outputs.mod_version == env.COMMIT_MESSAGE
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        if: steps.version.outputs.mod_version == env.COMMIT_MESSAGE
        uses: gradle/actions/setup-gradle@v4

      # This is needed to be able to run ./gradlew below
      # You can run `git update-index --chmod +x gradlew` then remove this step.
      - name: Make Gradle wrapper executable
        if: steps.version.outputs.mod_version == env.COMMIT_MESSAGE
        run: chmod +x ./gradlew

      - name: Build with Gradle
        if: steps.version.outputs.mod_version == env.COMMIT_MESSAGE
        run: ./gradlew build
#
#      - name: Delete current workflow run when version does not match
#        if: steps.version.outputs.mod_version != env.COMMIT_MESSAGE
#        uses: actions/github-script@v7
#        with:
#          script: |
#            await github.rest.actions.deleteWorkflowRun({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              run_id: context.runId,
#            });
