name: Build

on:
  push:

permissions:
  actions: write

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_MESSAGE: ${{ github.event.head_commit.name }}
      MOD_VERSION: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: gradle.properties
          property: mod_version
          default: 1.0.0
  build:
    needs: pre
    if: needs.pre.outputs.MOD_VERSION == needs.pre.outputs.COMMIT_MESSAGE
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Mod Metadata generated with Gradle
        run: ./gradlew generateModMetadata

      - name: Data Generated with Gradle
        run: ./gradlew runData

      - name: Build with Gradle
        run: ./gradlew build